
-- Insert Infection Control section
INSERT INTO public.sections (id, name, description, color_theme, "order")
VALUES (
  'c3d4e5f6-a7b8-9012-cdef-ab3456789012',
  'Infection Control',
  'Master the science of sanitation, disinfection, and safety. This section covers every microorganism, cleaning procedure, and safety protocol you need to know for your state board exam and your career as a licensed professional.',
  'teal',
  3
);

-- Block 1: General Microorganisms
INSERT INTO public.terms (section_id, block_number, "order", term, definition, metaphor, affirmation) VALUES
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 1, 1, 'Bacteria', 'Bacteria are microscopic, single celled organisms that exist almost everywhere in the environment, including on the skin, in the air, in water, and on surfaces. Some bacteria are harmless or even beneficial to the body, while others can cause infections or disease if they enter the body through cuts, openings, or contaminated tools. In a salon environment, proper cleaning and disinfection procedures are necessary to prevent harmful bacteria from spreading between clients.', 'Think of bacteria like invisible guests that are always present in a room. Some guests are welcome and cause no trouble. Others can create problems if they are not managed properly. Your job as a professional is to make sure only the safe guests are allowed to stay.', 'I understand that bacteria are everywhere and that my knowledge of proper sanitation keeps my clients safe.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 1, 2, 'Virus', 'A virus is a very small infectious microorganism that can only reproduce inside living cells. Viruses cannot survive for long outside a host, but when they enter the body they can multiply quickly and cause illness. Viral infections can spread through contact with bodily fluids, contaminated surfaces, or direct skin contact. Because viruses are not living cells like bacteria, they cannot be killed with antibiotics, making sanitation and prevention especially important.', 'Imagine a virus like a seed that cannot grow on its own. It needs to find the right soil, which is a living cell, before it can take root and spread. Without that host, the seed dries up and dies. Prevention is about making sure the seed never finds its soil.', 'I understand how viruses spread and I know that prevention through proper sanitation is the most powerful tool I have.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 1, 3, 'Fungus', 'Fungi are simple plant like organisms that include molds, mildews, and yeasts. They thrive in warm, moist environments and can cause infections of the skin, hair, or nails. Common fungal infections include athlete''s foot and ringworm. In a salon, fungi can spread through shared tools, contaminated surfaces, or unsanitary conditions if proper disinfection practices are not followed.', 'Think of fungi like mold growing on bread left in a warm, damp cabinet. The conditions create the perfect environment for growth. In the same way, warm and moist salon tools can become breeding grounds for fungal organisms if they are not properly cleaned and dried.', 'I recognize the conditions that allow fungi to grow and I take the steps necessary to keep my workspace clean and dry.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 1, 4, 'Parasite', 'A parasite is an organism that lives on or inside another living organism, called the host, and survives by feeding on that host. Parasites can cause irritation, infection, or disease in humans. An example relevant to cosmetology is head lice, which live on the scalp and feed on blood from the host. Proper sanitation and client screening help prevent the spread of parasitic infestations in salon environments.', 'A parasite is like an uninvited houseguest who moves in, eats your food, and never pays rent. The host provides everything the parasite needs to survive. Your role as a professional is to recognize the signs and protect your clients from these unwelcome visitors.', 'I can identify signs of parasitic conditions and I know the proper steps to protect my clients and my workspace.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 1, 5, 'Pathogen', 'A pathogen is any microorganism capable of causing disease in humans. Pathogens include certain bacteria, viruses, fungi, and parasites. When pathogens enter the body and multiply, they can lead to infections or illnesses. Preventing the spread of pathogens is one of the main goals of infection control practices in cosmetology.', 'Think of a pathogen as the villain in a story. Not every character is harmful, but the pathogen is the one that causes trouble when it gets past the defenses. Your job is to be the gatekeeper who stops the villain from getting through.', 'I understand what pathogens are and I am confident in my ability to prevent their spread through proper infection control.');

-- Block 2: Types of Bacteria
INSERT INTO public.terms (section_id, block_number, "order", term, definition, metaphor, affirmation) VALUES
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 2, 1, 'Nonpathogenic Bacteria', 'Nonpathogenic bacteria are harmless bacteria that do not cause disease. Many of these microorganisms are naturally present on the skin and in the environment and can even support normal biological processes. In a salon environment, these bacteria generally do not pose a health risk unless conditions allow harmful organisms to grow.', 'Nonpathogenic bacteria are like friendly neighbors who live on the same street as you. They mind their own business, they do not cause any harm, and some even help keep the neighborhood running smoothly.', 'I understand that not all bacteria are harmful and I can distinguish between nonpathogenic and pathogenic organisms.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 2, 2, 'Pathogenic Bacteria', 'Pathogenic bacteria are harmful microorganisms that can cause infection or disease in humans. These bacteria may enter the body through cuts, abrasions, or contact with contaminated tools and surfaces. Because pathogenic bacteria can spread quickly in environments where tools are shared, proper sanitation and disinfection procedures are essential in cosmetology practice.', 'Pathogenic bacteria are like troublemakers who sneak in through an open door. Once inside, they can cause real damage. Your sanitation practices are the locks and alarms that keep the troublemakers out.', 'I take pathogenic bacteria seriously and I follow every step of proper sanitation to protect my clients.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 2, 3, 'Cocci', 'Cocci are round shaped bacteria that commonly appear in groups or clusters. They are responsible for several common infections and can spread through direct contact, coughing, sneezing, or contaminated surfaces. Some types of cocci bacteria are responsible for conditions such as strep throat or other bacterial infections.', 'Picture cocci like tiny marbles scattered on a table. They are perfectly round and tend to cluster together in groups. When you hear cocci, think round, and remember that these little spheres can cause big infections if they spread.', 'I can identify cocci as round shaped bacteria and I understand how they spread in shared environments.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 2, 4, 'Bacilli', 'Bacilli are rod shaped bacteria that are widely found in dust, soil, water, and the air. Some bacilli are harmless while others can cause disease. These bacteria are often associated with infections that enter the body through wounds or contaminated surfaces.', 'Think of bacilli like tiny sticks or rods lined up in a row. They are everywhere, from the soil beneath your feet to the dust in the air. Some are harmless and some are not, which is why keeping surfaces clean matters so much.', 'I recognize bacilli as rod shaped bacteria and I understand the importance of cleaning surfaces where they may be present.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 2, 5, 'Spirilla', 'Spirilla are spiral shaped bacteria that are capable of movement and are responsible for certain infectious diseases. They are less common than cocci and bacilli but can still cause serious infections if transmitted to humans.', 'Imagine spirilla like tiny corkscrews spinning through liquid. Their spiral shape allows them to move quickly, which makes them efficient at finding a host. Though less common, they are powerful reminders that bacteria come in many forms.', 'I understand that spirilla are spiral shaped bacteria and I appreciate that bacteria exist in many different forms.');

-- Block 3: Movement and Infection
INSERT INTO public.terms (section_id, block_number, "order", term, definition, metaphor, affirmation) VALUES
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 3, 1, 'Flagella', 'Flagella are long, thread like structures that extend from certain bacteria and allow them to move through liquids. This movement helps bacteria spread more easily in environments where moisture is present.', 'Think of flagella like tiny propellers on a boat. They spin and push the bacteria forward through liquid, helping it travel to new locations. Where there is moisture, flagella help bacteria get around.', 'I understand that flagella give certain bacteria the ability to move through moisture, which is why keeping tools dry and clean is important.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 3, 2, 'Infection', 'An infection occurs when harmful microorganisms enter the body, multiply, and begin to damage tissue or disrupt normal body functions. The body often responds with inflammation, redness, swelling, or pain as it attempts to fight off the invading organisms.', 'An infection is like an uninvited army that breaks through the castle walls. Once inside, the invaders start causing damage, and the castle sends out its own soldiers to fight back. The redness, swelling, and pain you see are signs of that battle.', 'I understand how infections develop and I recognize the signs that the body is fighting harmful microorganisms.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 3, 3, 'Contagious Disease', 'A contagious disease is an illness that can spread from one person to another through direct contact, indirect contact, or exposure to contaminated objects or surfaces. In salon settings, contagious diseases can spread if proper sanitation and infection control procedures are not followed.', 'A contagious disease is like a rumor that spreads from person to person. One person tells another, and soon it has traveled across the entire room. In a salon, proper sanitation stops the spread before it can reach the next person.', 'I take contagious diseases seriously and I follow every infection control procedure to protect everyone in my workspace.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 3, 4, 'Inflammation', 'Inflammation is the body''s protective response to injury or infection. It is typically characterized by redness, heat, swelling, and pain in the affected area. Inflammation helps the body fight infection and begin the healing process.', 'Inflammation is like a fire alarm going off in a building. The alarm itself is not the problem. It is the signal that something needs attention. Redness, heat, and swelling are the body''s way of saying help is on the way.', 'I recognize inflammation as the body''s natural defense system and I understand the four signs: redness, heat, swelling, and pain.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 3, 5, 'Pus', 'Pus is a thick fluid produced by the body during an infection. It contains dead white blood cells, bacteria, and tissue debris. The presence of pus usually indicates that the body is actively fighting an infection.', 'Pus is like the cleanup crew arriving after a battle. The white blood cells fought the invading bacteria, and pus is what remains after the fight. It is a sign that the body is doing its job to heal.', 'I understand that pus is a sign the body is fighting infection, and I know to follow proper protocols when I see it.');

-- Block 4: Bloodborne Pathogens and Cleaning
INSERT INTO public.terms (section_id, block_number, "order", term, definition, metaphor, affirmation) VALUES
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 4, 1, 'Bloodborne Pathogens', 'Bloodborne pathogens are disease causing microorganisms that are present in human blood and can be transmitted through contact with infected blood or bodily fluids. These pathogens can enter the body through cuts, broken skin, or mucous membranes.', 'Bloodborne pathogens are like hidden dangers traveling through a river. You cannot see them with your eyes, but they are there. If that river touches an open wound, the danger can enter. Protective barriers and proper procedures are your dam against the flood.', 'I respect the serious nature of bloodborne pathogens and I always follow universal precautions to prevent exposure.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 4, 2, 'Hepatitis', 'Hepatitis is a viral infection that causes inflammation of the liver. Certain forms of hepatitis can be spread through contact with infected blood or bodily fluids. Because of the serious health risks associated with hepatitis, strict infection control procedures must be followed in salon environments.', 'Think of the liver as the body''s filter, cleaning everything that passes through. Hepatitis is like a virus that attacks the filter itself, making it inflamed and unable to do its job properly. Protecting against hepatitis means protecting one of the body''s most important organs.', 'I understand the seriousness of hepatitis and I follow strict protocols to prevent its transmission in my workspace.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 4, 3, 'HIV', 'HIV is a virus that attacks the immune system and weakens the body''s ability to fight infections and diseases. It is transmitted through blood and certain bodily fluids. While HIV cannot survive long outside the human body, proper safety precautions are necessary to prevent exposure.', 'HIV is like a saboteur that targets the body''s security team. By weakening the immune system, it leaves the body defenseless against other threats. Understanding how HIV spreads empowers you to prevent exposure through proper precautions.', 'I understand how HIV is transmitted and I am committed to following every safety precaution to protect myself and my clients.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 4, 4, 'Cleaning', 'Cleaning is the physical process of removing dirt, debris, and visible material from surfaces or tools. Cleaning is usually done with soap, detergent, and water and is the first step before disinfecting tools.', 'Cleaning is like sweeping the floor before you mop it. You have to remove the visible dirt first before you can go deeper with disinfection. Without cleaning first, disinfection cannot do its full job.', 'I understand that cleaning is the essential first step in every sanitation procedure and I never skip it.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 4, 5, 'Sanitation', 'Sanitation is the process of reducing the number of microorganisms on surfaces or tools to safe levels. This helps prevent the spread of infections in environments where people share equipment or spaces.', 'Sanitation is like turning down the volume on a speaker. You are not eliminating the sound completely, but you are bringing it to a safe level where it will not cause harm. Reducing microorganisms to safe levels is what sanitation is all about.', 'I understand that sanitation reduces microorganisms to safe levels and I apply this knowledge consistently in my practice.');

-- Block 5: Disinfection and Safety
INSERT INTO public.terms (section_id, block_number, "order", term, definition, metaphor, affirmation) VALUES
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 5, 1, 'Disinfection', 'Disinfection is the use of chemical products designed to destroy most harmful microorganisms on nonporous surfaces. Proper disinfection procedures are essential for tools and equipment used in cosmetology services.', 'Disinfection is like using a powerful cleaner that goes beyond the surface to destroy the invisible threats hiding underneath. While cleaning removes what you can see, disinfection eliminates what you cannot.', 'I understand the difference between cleaning and disinfection, and I know that disinfection destroys harmful microorganisms on my tools.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 5, 2, 'Sterilization', 'Sterilization is the highest level of decontamination and involves destroying all microorganisms, including bacteria, viruses, fungi, and spores. This process is typically used in medical settings but represents the highest standard of infection control.', 'Sterilization is like a complete reset. Imagine wiping a whiteboard so clean that not a single mark remains. Every microorganism, even the toughest spores, is completely eliminated. It is the gold standard of decontamination.', 'I understand that sterilization is the highest level of decontamination and I know where it falls in the hierarchy of infection control.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 5, 3, 'Hospital Disinfectant', 'A hospital disinfectant is a chemical product formulated to destroy microorganisms on nonporous surfaces. These disinfectants are commonly used in professional environments where sanitation standards are critical.', 'A hospital disinfectant is like the professional grade tools a mechanic uses compared to what you might find at home. It is designed for environments where the stakes are high and the standards are strict.', 'I know that hospital disinfectants are designed for professional environments and I use them according to manufacturer instructions.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 5, 4, 'Tuberculocidal Disinfectant', 'A tuberculocidal disinfectant is a type of disinfectant proven effective against the bacteria that cause tuberculosis. Because tuberculosis bacteria are difficult to destroy, products labeled tuberculocidal are considered strong disinfectants.', 'A tuberculocidal disinfectant is like the heavy duty lock on a vault door. It is built to handle the toughest challenges. If it can destroy tuberculosis bacteria, it can handle most other harmful organisms as well.', 'I understand that tuberculocidal disinfectants represent a higher level of effectiveness and I know when to use them in my practice.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 5, 5, 'Universal Precautions', 'Universal precautions are safety practices designed to prevent exposure to bloodborne pathogens. These guidelines require professionals to treat all blood and bodily fluids as potentially infectious and to follow protective procedures when handling tools or materials.', 'Universal precautions are like wearing a seatbelt every time you drive, not just when you think the road is dangerous. You treat every situation as if there could be a risk, because that is what keeps you and everyone around you safe.', 'I follow universal precautions at all times because treating every situation with care is what makes me a true professional.');

-- Block 6: Safety Documents
INSERT INTO public.terms (section_id, block_number, "order", term, definition, metaphor, affirmation) VALUES
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 6, 1, 'Exposure Incident', 'An exposure incident occurs when a person''s skin, eyes, mouth, or mucous membranes come into contact with blood or potentially infectious bodily fluids.', 'An exposure incident is like accidentally stepping into a puddle you did not see. The moment contact happens, you need to act quickly and follow the proper steps to minimize any risk.', 'I know what an exposure incident is and I am prepared to respond immediately and correctly if one occurs.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 6, 2, 'Safety Data Sheet', 'A Safety Data Sheet is a document that provides detailed information about chemical products, including their ingredients, potential hazards, safe handling procedures, and emergency measures.', 'A Safety Data Sheet is like the instruction manual that comes with a new appliance. It tells you exactly what is inside, how to use it safely, and what to do if something goes wrong. Every chemical product in your salon should have one.', 'I understand the purpose of Safety Data Sheets and I know where to find them for every chemical product in my workspace.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 6, 3, 'Material Safety Data Sheet', 'Material Safety Data Sheets were the earlier version of Safety Data Sheets. They served the same purpose of informing workers about chemical safety but have largely been replaced by the standardized SDS system.', 'An MSDS is like the original version of a recipe that has since been updated and standardized. The information is similar, but the newer SDS format is more consistent and easier to follow across all industries.', 'I know that MSDS was the earlier version of the SDS and I understand that both serve the important purpose of chemical safety communication.');
