
-- Quiz questions for Infection Control - Block 1
INSERT INTO public.questions (section_id, block_number, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 1, 'A cosmetology student is studying for the state board exam and wants to understand why antibiotics cannot be used to treat every type of infection. Which of the following microorganisms cannot be destroyed by antibiotics?', 'Bacteria', 'Viruses', 'Fungi', 'Nonpathogenic bacteria', 'B', 'Viruses are not living cells like bacteria, so antibiotics have no effect on them. This is why prevention through proper sanitation and disinfection is especially important when it comes to viral infections.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 1, 'A client arrives at the salon with a visible fungal infection on one of their nails. The cosmetologist knows that fungi thrive in specific environmental conditions. Which conditions are most likely to promote fungal growth?', 'Cold and dry environments', 'Warm and moist environments', 'Well ventilated and sunny spaces', 'Sterile and sealed containers', 'B', 'Fungi thrive in warm, moist environments. This is why proper disinfection and keeping tools dry is essential to preventing fungal infections from spreading in a salon.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 1, 'During a salon inspection, the inspector asks a cosmetologist to explain the difference between a pathogen and a nonpathogenic organism. Which of the following best describes a pathogen?', 'A harmless organism found on the skin', 'Any microorganism capable of causing disease', 'A chemical used to destroy bacteria', 'A type of fungus found in moist environments', 'B', 'A pathogen is any microorganism, including certain bacteria, viruses, fungi, and parasites, that is capable of causing disease in humans. Preventing the spread of pathogens is one of the main goals of infection control.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 1, 'A cosmetologist notices a client scratching their scalp frequently during a service. Upon closer inspection, small organisms are visible near the hair shaft. Which type of microorganism is most likely responsible?', 'Bacteria', 'Virus', 'Fungus', 'Parasite', 'D', 'Parasites such as head lice live on or inside a host organism and survive by feeding on it. Head lice live on the scalp and feed on blood. Proper client screening and sanitation help prevent the spread of parasitic infestations.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 1, 'A new cosmetology student asks why it is important to disinfect tools even when they appear clean. Which of the following is the best explanation?', 'Disinfection makes tools look shinier', 'Harmful microorganisms like bacteria can be present even when surfaces appear clean', 'Clients expect tools to smell like disinfectant', 'State law only requires tools to be cleaned once per day', 'B', 'Bacteria and other harmful microorganisms are microscopic and cannot be seen with the naked eye. Even when tools appear clean, pathogens may still be present. Proper disinfection destroys these invisible threats.');

-- Block 2
INSERT INTO public.questions (section_id, block_number, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 2, 'A cosmetology student is learning about the different shapes of bacteria. Which term describes bacteria that are round in shape and often appear in clusters?', 'Bacilli', 'Spirilla', 'Cocci', 'Flagella', 'C', 'Cocci are round shaped bacteria that commonly appear in groups or clusters. They are responsible for several common infections and can spread through contact, coughing, or contaminated surfaces.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 2, 'During a state board review, a student is asked which type of bacteria is rod shaped and commonly found in dust, soil, and water. Which of the following is the correct answer?', 'Cocci', 'Spirilla', 'Bacilli', 'Flagella', 'C', 'Bacilli are rod shaped bacteria that are widely found in dust, soil, water, and the air. Some bacilli are harmless while others can cause disease when they enter the body through wounds or contaminated surfaces.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 2, 'A cosmetologist explains to a new hire that not all bacteria are harmful. Which type of bacteria does not cause disease and is often found naturally on the skin?', 'Pathogenic bacteria', 'Spirilla', 'Nonpathogenic bacteria', 'Cocci', 'C', 'Nonpathogenic bacteria are harmless bacteria that do not cause disease. Many are naturally present on the skin and in the environment and can even support normal biological processes.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 2, 'A student is reviewing bacteria classifications and encounters spiral shaped bacteria. Which term correctly identifies this shape?', 'Bacilli', 'Cocci', 'Flagella', 'Spirilla', 'D', 'Spirilla are spiral shaped bacteria capable of movement. While less common than cocci and bacilli, they can cause serious infections if transmitted to humans.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 2, 'Which of the following statements best describes pathogenic bacteria?', 'They are always found inside the human body', 'They are harmful microorganisms that can cause infection or disease', 'They are only found in hospital environments', 'They are the same as viruses', 'B', 'Pathogenic bacteria are harmful microorganisms that can cause infection or disease in humans. They may enter through cuts, abrasions, or contaminated tools, which is why proper sanitation is essential.');

-- Block 3
INSERT INTO public.questions (section_id, block_number, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 3, 'A cosmetology student learns that certain bacteria can move through liquids using special structures. What are these thread like structures called?', 'Spirilla', 'Cocci', 'Flagella', 'Bacilli', 'C', 'Flagella are long, thread like structures that extend from certain bacteria and allow them to move through liquids. This movement helps bacteria spread more easily in moist environments.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 3, 'A client comes into the salon with redness, swelling, and warmth around a small cut on their hand. Which of the following best describes what is happening in the body?', 'An allergic reaction to a product', 'The body is experiencing inflammation as a protective response', 'The client has a contagious disease', 'The skin is reacting to cold temperatures', 'B', 'Inflammation is the body''s protective response to injury or infection. It is characterized by redness, heat, swelling, and pain. These signs indicate the body is fighting infection and beginning the healing process.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 3, 'During a state board exam review, a student is asked to explain what happens when harmful microorganisms enter the body and begin to multiply. Which term best describes this process?', 'Inflammation', 'Sanitation', 'Infection', 'Disinfection', 'C', 'An infection occurs when harmful microorganisms enter the body, multiply, and begin to damage tissue or disrupt normal body functions. The body often responds with inflammation as it attempts to fight off the invaders.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 3, 'A cosmetologist suspects that a client may have a condition that could spread to other clients. Which term describes an illness that can be transmitted from one person to another?', 'Inflammation', 'Infection', 'Contagious disease', 'Sterilization', 'C', 'A contagious disease is an illness that can spread from one person to another through direct or indirect contact, or through contaminated surfaces. Proper sanitation prevents the spread of contagious diseases in salon settings.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 3, 'A student notices a thick fluid around a healing wound on a mannequin training model and asks the instructor what it represents. The instructor explains that this fluid is produced during an active infection. What is this fluid called?', 'Sebum', 'Plasma', 'Pus', 'Lymph', 'C', 'Pus is a thick fluid produced by the body during an infection. It contains dead white blood cells, bacteria, and tissue debris. The presence of pus usually indicates the body is actively fighting an infection.');

-- Block 4
INSERT INTO public.questions (section_id, block_number, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 4, 'A cosmetologist accidentally cuts a client during a service and blood is exposed. Which type of microorganisms present in blood pose the greatest concern in this situation?', 'Nonpathogenic bacteria', 'Fungi', 'Bloodborne pathogens', 'Spirilla', 'C', 'Bloodborne pathogens are disease causing microorganisms present in human blood that can be transmitted through contact with infected blood or bodily fluids. Proper safety protocols must be followed immediately during any blood exposure.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 4, 'During infection control training, a cosmetology student learns about a viral infection that causes inflammation of the liver and can be transmitted through blood. Which condition is being described?', 'HIV', 'Tuberculosis', 'Hepatitis', 'Ringworm', 'C', 'Hepatitis is a viral infection that causes inflammation of the liver. Certain forms can be spread through contact with infected blood or bodily fluids, making strict infection control procedures essential in salon environments.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 4, 'A cosmetology instructor explains the proper order of decontamination to a new class. Which step must always come first before disinfecting tools?', 'Sterilization', 'Sanitation', 'Cleaning', 'Applying universal precautions', 'C', 'Cleaning is the physical process of removing dirt, debris, and visible material from surfaces or tools using soap and water. It is always the first step before disinfection because disinfectants cannot work effectively on visibly dirty surfaces.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 4, 'Which of the following best describes the process of reducing microorganisms on surfaces to safe levels?', 'Sterilization', 'Sanitation', 'Cleaning', 'Universal precautions', 'B', 'Sanitation is the process of reducing the number of microorganisms on surfaces or tools to safe levels. It helps prevent the spread of infections in environments where people share equipment.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 4, 'A cosmetology student is studying HIV and wants to understand how it affects the body. Which of the following best describes the impact of HIV?', 'It causes inflammation of the liver', 'It attacks the immune system and weakens the body''s ability to fight disease', 'It causes spiral shaped bacteria to multiply', 'It destroys all bacteria on the skin', 'B', 'HIV attacks the immune system and weakens the body''s ability to fight infections and diseases. It is transmitted through blood and certain bodily fluids, making proper safety precautions essential.');

-- Block 5
INSERT INTO public.questions (section_id, block_number, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 5, 'A cosmetology student is learning about the different levels of decontamination. Which level destroys all microorganisms including spores and represents the highest standard of infection control?', 'Cleaning', 'Sanitation', 'Disinfection', 'Sterilization', 'D', 'Sterilization is the highest level of decontamination and involves destroying all microorganisms, including bacteria, viruses, fungi, and spores. It is typically used in medical settings and represents the gold standard of infection control.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 5, 'A salon owner purchases a disinfectant labeled as tuberculocidal. What does this label indicate about the product?', 'It can only be used on porous surfaces', 'It is effective against the bacteria that cause tuberculosis', 'It is the same as a regular cleaning product', 'It requires no contact time to be effective', 'B', 'A tuberculocidal disinfectant is proven effective against the bacteria that cause tuberculosis. Because TB bacteria are particularly difficult to destroy, tuberculocidal products are considered strong and reliable disinfectants.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 5, 'Which of the following best describes universal precautions in a salon environment?', 'Wearing gloves only when a client has a visible wound', 'Treating all blood and bodily fluids as potentially infectious', 'Disinfecting tools once at the end of the day', 'Using antibiotics to prevent infection', 'B', 'Universal precautions require professionals to treat all blood and bodily fluids as potentially infectious and to follow protective procedures at all times. This approach ensures safety regardless of whether a specific risk is visible.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 5, 'What is the primary purpose of disinfection in a cosmetology setting?', 'To make tools look clean and polished', 'To destroy most harmful microorganisms on nonporous surfaces', 'To remove visible dirt from surfaces', 'To sterilize all salon equipment', 'B', 'Disinfection uses chemical products to destroy most harmful microorganisms on nonporous surfaces. It goes beyond cleaning by eliminating invisible threats that remain after visible dirt has been removed.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 5, 'A cosmetology student asks the instructor which type of disinfectant is commonly used in professional environments where sanitation standards are critical. What is the correct answer?', 'Household cleaner', 'Hospital disinfectant', 'Hand sanitizer', 'Antibacterial soap', 'B', 'Hospital disinfectants are chemical products formulated to destroy microorganisms on nonporous surfaces. They are designed for professional environments where high sanitation standards are required.');

-- Block 6
INSERT INTO public.questions (section_id, block_number, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 6, 'During a salon service, a cosmetologist accidentally nicks a client and blood comes into contact with the cosmetologist''s ungloved hand. Which term best describes this situation?', 'Universal precaution', 'Exposure incident', 'Sanitation failure', 'Contagious disease', 'B', 'An exposure incident occurs when a person''s skin, eyes, mouth, or mucous membranes come into contact with blood or potentially infectious bodily fluids. Immediate response following proper protocols is essential.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 6, 'A cosmetology student needs to find information about the ingredients and hazards of a chemical product used in the salon. Which document should they consult?', 'Client intake form', 'Safety Data Sheet', 'Salon license certificate', 'State board regulation handbook', 'B', 'A Safety Data Sheet provides detailed information about chemical products including their ingredients, potential hazards, safe handling procedures, and emergency measures. Every chemical product in a salon should have an accessible SDS.'),
('c3d4e5f6-a7b8-9012-cdef-ab3456789012', 6, 'What is the relationship between a Material Safety Data Sheet and a Safety Data Sheet?', 'They are completely different documents with different purposes', 'An MSDS is the earlier version of the SDS that has been replaced by the standardized format', 'An SDS is used only in hospitals while an MSDS is used in salons', 'An MSDS contains more detailed information than an SDS', 'B', 'Material Safety Data Sheets were the earlier version of Safety Data Sheets. They served the same purpose of informing workers about chemical safety but have been replaced by the standardized SDS system for consistency across industries.');
